apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: syedcommitrepos 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: syedcommitrepos 
    spec:
      containers:
        - name: syedcommitrepos 
          image: mycontainerregistry20.azurecr.io/syedcommitrepos
          ports:
          - containerPort: 8080